### ISSUE TITLE
only playable with Sonic?

### ISSUE THREAD

**Issue by ociebieda** [gmarty/jsSMS#4]
I tested out jsSMS with over 200 roms for SMS and GG.
I used Chrome, FireFox and Opera.
Is that emulator in very early pre-alpha phase?
I was able to run only Sonic The Hedgehog (for both SMS and GG) and other roms made black screen or didnt go above title screen which in most cases was frozen.
When looking to console, I noticed many throws of unsupported instructions (I guess Z80 or graphics).
I know that there is Miracle, but it does not support GG.

**Comment by gmarty** [comment]
Looks like this issue can be closed.
